version: '3'

services:
  linkwave-db:
    image: postgres:latest
    container_name: linkwave-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: linkwave_user
      POSTGRES_PASSWORD: ndquang@2002
      POSTGRES_DB: linkwave_db
    ports:
      - "5005:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - linkwave-network

  linkwave-keycloak:
    image: bitnami/keycloak:22.0.5
    depends_on:
      - keycloak-db
    container_name: linkwave-keycloak
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak_db
      DB_USER: linkwave_user
      DB_PASSWORD: ndquang@2002
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-export.json:/opt/bitnami/keycloak/data/import/realm-export.json
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - linkwave-network

  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    restart: unless-stopped
    ports:
      - "5006:5432"
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: linkwave_user
      POSTGRES_PASSWORD: ndquang@2002
    networks:
      - linkwave-network

volumes:
  postgres_data:

networks:
  linkwave-network:
    driver: bridge
