version: '3'

services:
  linkwave-db:
    image: postgres:15
    container_name: linkwave-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: linkwave_user
      POSTGRES_PASSWORD: ndquang@2002
      POSTGRES_DB: linkwave_db
    ports:
      - "5005:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - linkwave-network

  linkwave-keycloak:
    image: bitnami/keycloak:22.0.5
    depends_on:
      - keycloak-db
    container_name: linkwave-keycloak
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak_db
      DB_USER: linkwave_user
      DB_PASSWORD: ndquang@2002
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-export.json:/opt/bitnami/keycloak/data/import/realm-export.json
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - linkwave-network

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    restart: unless-stopped
    ports:
      - "5008:5432"
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: linkwave_user
      POSTGRES_PASSWORD: ndquang@2002
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - linkwave-network

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
    networks:
      - linkwave-network

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: unless-stopped
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    networks:
      - linkwave-network

volumes:
  postgres_data:
    driver: local
  keycloak-db-data:
    driver: local

networks:
  linkwave-network:
    driver: bridge
