version: '3'

services:
  linkwave-app:
    build: ./
    container_name: linkwave-application
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - linkwave-network
    depends_on:
      - linkwave-db

  linkwave-db:
    image: postgres:14
    container_name: linkwave-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: linkwave
      POSTGRES_PASSWORD: ndquang@2002
      POSTGRES_DB: linkwave
    ports:
      - "5005:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - linkwave-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ndquang5802@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ndquang@2002
    ports:
      - "5050:80"
    networks:
      - linkwave-network

  linkwave-keycloak:
    image: bitnami/keycloak:21
    depends_on:
      - keycloak-db
    container_name: linkwave-keycloak
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: linkwave
      DB_PASSWORD: ndquang@2002
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-export.json:/opt/bitnami/keycloak/data/import/realm-export.json
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - linkwave-network

  keycloak-db:
    image: postgres:14
    container_name: keycloak-db
    restart: unless-stopped
    ports:
      - "5006:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: linkwave
      POSTGRES_PASSWORD: ndquang@2002
    networks:
      - linkwave-network

volumes:
  postgres_data:

networks:
  linkwave-network:
    driver: bridge
