spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    locations:
      - classpath:db/migration/schema
      - classpath:db/migration/data
    clean-on-validation-error: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true
        show_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/linkwave
          jwk-set-uri: ${KEYCLOAK_URL}/realms/linkwave/protocol/openid-connect/certs
  data:
    rest:
      base-path: /api
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

server:
  port: 8080

jwt:
  auth:
    converter:
      principle-attribute: preferred_username

keycloak:
    url: ${KEYCLOAK_URL}
    realm: master
    master-client-id: admin-cli #for master realm
    client-id: document-client
    username: ${KEYCLOAK_USERNAME}
    password: ${KEYCLOAK_PASSWORD}
    roles: SUPER_ADMIN, ADMIN, USER
    defaultRole: USER
    token-life-span: ${KEYCLOAK_TOKEN_LIFE_SPAN}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}